# Generated by Django 6.0 on 2026-05-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="تم الدفع"),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="إجمالي الطلب"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="سعر القطعة"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default="", max_length=10, verbose_name="المقاس"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المعالجة"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=50,
                verbose_name="حالة الطلب",
            ),
        ),
    ]
