# Generated by Django 6.0 on 2025-12-30 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='المخزون العام'),
        ),
        migrations.CreateModel(
            name='RingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='المقاس')),
                ('system', models.CharField(choices=[('US', 'US'), ('EU', 'EU')], default='US', max_length=10, verbose_name='نظام المقاس')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مقاس خاتم',
                'verbose_name_plural': 'مقاسات الخواتم',
                'ordering': ['size'],
            },
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
